# Generated by Django 3.1.7 on 2021-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('str_model', models.CharField(blank=True, max_length=255, null=True)),
                ('str_ram', models.CharField(blank=True, max_length=255, null=True)),
                ('str_memory', models.CharField(blank=True, max_length=255, null=True)),
                ('str_camera', models.CharField(blank=True, max_length=255, null=True)),
                ('str_battery', models.CharField(blank=True, max_length=255, null=True)),
                ('str_processor', models.CharField(blank=True, max_length=255, null=True)),
                ('int_price', models.IntegerField()),
                ('img_image', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
    ]
